import type { RouteProps } from '../../core/domain/route.js';

export const INITIAL_ROUTES: RouteProps[] = [
  {
    id: 'R001',
    vesselType: 'Container',
    fuelType: 'HFO',
    year: 2024,
    ghgIntensityGco2ePerMj: 91.0,
    fuelConsumptionTonnes: 5000,
    distanceKm: 12000,
    totalEmissionsTonnes: 4500,
    isBaseline: true,
  },
  {
    id: 'R002',
    vesselType: 'BulkCarrier',
    fuelType: 'LNG',
    year: 2024,
    ghgIntensityGco2ePerMj: 88.0,
    fuelConsumptionTonnes: 4800,
    distanceKm: 11500,
    totalEmissionsTonnes: 4200,
    isBaseline: false,
  },
  {
    id: 'R003',
    vesselType: 'Tanker',
    fuelType: 'MGO',
    year: 2024,
    ghgIntensityGco2ePerMj: 93.5,
    fuelConsumptionTonnes: 5100,
    distanceKm: 12500,
    totalEmissionsTonnes: 4700,
    isBaseline: false,
  },
  {
    id: 'R004',
    vesselType: 'RoRo',
    fuelType: 'HFO',
    year: 2025,
    ghgIntensityGco2ePerMj: 89.2,
    fuelConsumptionTonnes: 4900,
    distanceKm: 11800,
    totalEmissionsTonnes: 4300,
    isBaseline: true,
  },
  {
    id: 'R005',
    vesselType: 'Container',
    fuelType: 'LNG',
    year: 2025,
    ghgIntensityGco2ePerMj: 90.5,
    fuelConsumptionTonnes: 4950,
    distanceKm: 11900,
    totalEmissionsTonnes: 4400,
    isBaseline: false,
  },
  {
    id: 'R006',
    vesselType: 'Tanker',
    fuelType: 'MGO',
    year: 2025,
    ghgIntensityGco2ePerMj: 87.9,
    fuelConsumptionTonnes: 4720,
    distanceKm: 11250,
    totalEmissionsTonnes: 4050,
    isBaseline: false,
  },
];
